console.log(' ')
console.log(' ')
console.log('Oi Guto, tudo bem? Estudando bastante? Que bom. Segue aí que eu sigo daqui')
console.log('Intressante. Para exibir este código no Terminal, basta copiar o path na saída do Visual Studio e colar no Terminal. Nesse caso, o path é "node "/Users/user/Desktop/JAVASCRIPT-UDEMY/se2-aula12/index.js"". Não esquecer de inserir o "node" antes do caminho.')
console.log(' ')
console.log(' ')
alert('Olá Mundo')